-- local keymap = vim.keymap
-- local status, tree = pcall(require, 'nvim-tree')
-- if not status then
-- 	print "Did not local nvim-tree plugin"
-- 	return
-- end
--
-- local icons = {
-- 	diagnostics = require("icons").get("diagnostics"),
-- 	documents = require("icons").get("documents"),
-- 	git = require("icons").get("git"),
-- 	ui = require("icons").get("ui"),
-- }
--
-- tree.setup({
-- 	view = {
-- 		float = {
-- 			enable = true,
-- 			open_win_config = {
-- 				relative = "editor",
-- 				width = 40,
-- 				height = 25,
-- 				row = 1,
-- 				col = 1,
-- 			},
-- 		},
-- 	},
-- 	renderer = {
-- 		highlight_opened_files = "none",
-- 		special_files = { "index.js", "index.ts", "index.jsx", "index.tsx", "Cargo.toml", "Makefile", "README.md",
-- 			"readme.md", "Readme.md", "CMakeLists.txt" },
-- 		symlink_destination = true,
-- 		indent_markers = {
-- 			enable = true,
-- 			icons = {
-- 				corner = "└ ",
-- 				edge = "│ ",
-- 				item = "│ ",
-- 				none = "  ",
-- 			},
-- 		},
-- 		-- root_folder_label = ":.:s?.*?/..?",
-- 		root_folder_label = false,
-- 		icons = {
-- 			git_placement = "after",
-- 			padding = " ",
-- 			symlink_arrow = " 󰁔 ",
-- 			glyphs = {
-- 				default = icons.documents.Default,
-- 				symlink = icons.documents.Symlink,
-- 				bookmark = icons.ui.Bookmark,
-- 				git = {
-- 					unstaged = icons.git.Mod_alt,
-- 					staged = icons.git.Add,
-- 					unmerged = icons.git.Unmerged,
-- 					renamed = icons.git.Rename,
-- 					untracked = icons.git.Untracked,
-- 					deleted = icons.git.Remove,
-- 					ignored = icons.git.Ignore,
-- 				},
-- 				folder = {
-- 					arrow_open = icons.ui.ArrowOpen,
-- 					arrow_closed = icons.ui.ArrowClosed,
-- 					default = icons.ui.Folder,
-- 					open = icons.ui.FolderOpen,
-- 					empty = icons.ui.EmptyFolder,
-- 					empty_open = icons.ui.EmptyFolderOpen,
-- 					symlink = icons.ui.SymlinkFolder,
-- 					symlink_open = icons.ui.FolderOpen,
-- 				},
-- 			},
-- 		},
-- 	},
-- 	update_focused_file = {
-- 		enable = true,
-- 		update_root = false,
-- 	},
-- 	filesystem_watchers = {
-- 		enable = true,
-- 	},
-- 	filters = {
-- 		custom = { ".DS_Store" },
-- 		git_ignored = false,
-- 		dotfiles = false,
-- 	},
-- 	sync_root_with_cwd = true,
-- 	diagnostics = {
-- 		enable = true,
-- 		show_on_dirs = true,
-- 		debounce_delay = 50,
-- 		icons = {
-- 			hint = icons.diagnostics.Hint_alt,
-- 			info = icons.diagnostics.Information_alt,
-- 			warning = icons.diagnostics.Warning_alt,
-- 			error = icons.diagnostics.Error_alt,
-- 		},
-- 	},
-- })
--
-- keymap.set('n', '<C-n>o', ':NvimTreeFocus<Return>', { desc = 'Nvim Tree: Open and focus' })
-- keymap.set('n', '<C-n>t', ':NvimTreeToggle<Return>', { desc = 'Nvim Tree: Toggle open/closed' })
-- keymap.set('n', '<C-n>f', ':NvimTreeFindFile<Return>', { desc = 'Nvim Tree: Find and focus current file' })
-- keymap.set('n', '<C-n>c', ':NvimTreeCollapse<Return>', { desc = 'Nvim Tree: Collapse all folders' })
