os:
  editPreset: "nvim"
  edit: "nvim {{filename}}"
  editCommand: "nvim"
  editCommandTemplate: "nvim {{filename}}"
gui:
  windowSize: "normal"
  showBranchCommitHash: true
  showBottomLine: false
  nerdFontsVersion: "3"
  showRandomTip: false
  splitDiff: "auto"
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - "#F38BA8" # Red
customCommands:
  - key: "z"
    command: "git-cz"
    description: "Make a commit using commitizen"
    context: "files"
    loadingText: "Opening commitizen..."
    subprocess: true
